name: Deploy to AWS
on: [ workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: ./ci/install-deps.sh
      - run: ./ci/build-all.sh
      - run: exports AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} AWS_DEFAULT_REGION=ap-southeast-2 cd spineless-infra && npx cdk deploy --require-approval never "spineless-stack"
