name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: which node
      - run: which yarn
      - run: ./ci/build-all.sh
