name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: ls -l ci
      - run: which node
      - run: which yarn
      - run: ./ci/build-all.sh
